# numpy

- one of the core packages for numerical computing in python
- many packages are built on topy numpy 
- numpy has been optimized for processing: faster due to memory access



In [4]:
# import Numpy with standard abbreviation
import numpy as np

# Variables
We can think about variables as a name we assign to a particula object in Python. For example

In [9]:
# assign a sall array to a variable a
a = np.array( [[1,1,2], [3,5,8] ] )


[[1 1 2]
 [3 5 8]]


In [10]:
print(a)

[[1 1 2]
 [3 5 8]]


## Naming variables
In the class we are going to yse 'snake_case' for naming variables.

## Variables and objects

**objects**: often encountered in Python documentation and tutorials

object is  abundle of properties and actions about something specific
Example: 

- object: data frame
- properties: number of rows, names of columns, data created
- actions: selecting a row, adding a column

A variable is a name we give a specific object, and the same object can be referenced by different variables.

Ex: 

- The Sun = object
- sol = Spanish word for Sun = variable
- soleil = French for Sun = another variable

In practice we will use object and variable interchangeably 

# Types
Each object in Python has a type. 

type = what kind of object it is 

We can also call the type of the object, the **class** of the object.

We can see the type/class of an object using the type fuction

In [12]:
print(a)
type(a)

[[1 1 2]
 [3 5 8]]


numpy.ndarray

The 'numpy.ndarray' is the core object.data type in the NumpPy package. We can check the type of an entry in the array by indexing:

In [17]:
print(a[0,0])  ## access the first row and the first column

type(a[0,0])  ## type of that number 

1


numpy.int64

In [19]:
## access the 5, second row and second column 
print(a[1,1])

5


# Functions

`print` was our example of a Python function! :)

A function: 
- take

argument = paramter 

In [ ]:
?print

- first line: function showing all of its arguments in paranthesus
- then a short description of what the function does
- finally, a list of the arguments and a brief explanation of each of them

Different types of arguments inside the parenthesis. Roughly speaking, there are two types of arguments:

- **non-optional arguments**: arguments you need to specifu for the function to do something
- **optional arguments**: argyments that are pre-filled with a default value by the function, but we can ovveride them. Optional arguments appear inside the parenthesis () in the form

`optional argument = default_value`

In [ ]:
print('changing the default end argument of the print function', end = ':)'